# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/SEREF/Desktop/DeepPy/V_5/design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 920)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_data_selection = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_data_selection.setGeometry(QtCore.QRect(570, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_data_selection.setFont(font)
        self.pushButton_data_selection.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_data_selection.setObjectName("pushButton_data_selection")
        self.pushButton_model_selection = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_model_selection.setGeometry(QtCore.QRect(150, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_model_selection.setFont(font)
        self.pushButton_model_selection.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_model_selection.setObjectName("pushButton_model_selection")
        self.pushButton_train = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_train.setGeometry(QtCore.QRect(990, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_train.setFont(font)
        self.pushButton_train.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_train.setObjectName("pushButton_train")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 110, 1251, 721))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.model_selection = QtWidgets.QWidget()
        self.model_selection.setObjectName("model_selection")
        self.comboBox = QtWidgets.QComboBox(self.model_selection)
        self.comboBox.setGeometry(QtCore.QRect(40, 280, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit_2.setGeometry(QtCore.QRect(860, 260, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit_3.setGeometry(QtCore.QRect(860, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit_4.setGeometry(QtCore.QRect(860, 380, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit.setGeometry(QtCore.QRect(960, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_layer = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit_layer.setGeometry(QtCore.QRect(1050, 260, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_layer.setFont(font)
        self.lineEdit_layer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_layer.setText("")
        self.lineEdit_layer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_layer.setReadOnly(True)
        self.lineEdit_layer.setObjectName("lineEdit_layer")
        self.lineEdit_input = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit_input.setGeometry(QtCore.QRect(1050, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_input.setFont(font)
        self.lineEdit_input.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_input.setText("")
        self.lineEdit_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_input.setReadOnly(True)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.lineEdit_output = QtWidgets.QLineEdit(self.model_selection)
        self.lineEdit_output.setGeometry(QtCore.QRect(1050, 380, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_output.setFont(font)
        self.lineEdit_output.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 95, 147, 243), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 189, 255));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_output.setText("")
        self.lineEdit_output.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_output.setReadOnly(True)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.scrollArea = QtWidgets.QScrollArea(self.model_selection)
        self.scrollArea.setGeometry(QtCore.QRect(340, 30, 451, 661))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 659))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.model_selection)
        self.data_selection = QtWidgets.QWidget()
        self.data_selection.setObjectName("data_selection")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 80, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_import = QtWidgets.QPushButton(self.data_selection)
        self.pushButton_import.setGeometry(QtCore.QRect(180, 630, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_import.setObjectName("pushButton_import")
        self.label = QtWidgets.QLabel(self.data_selection)
        self.label.setGeometry(QtCore.QRect(10, 180, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.data_selection)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.data_selection)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.data_selection)
        self.checkBox.setGeometry(QtCore.QRect(220, 240, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.data_selection)
        self.checkBox_2.setGeometry(QtCore.QRect(280, 240, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_4 = QtWidgets.QLabel(self.data_selection)
        self.label_4.setGeometry(QtCore.QRect(10, 310, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.data_selection)
        self.spinBox.setGeometry(QtCore.QRect(320, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(55)
        self.spinBox.setObjectName("spinBox")
        self.label_5 = QtWidgets.QLabel(self.data_selection)
        self.label_5.setGeometry(QtCore.QRect(20, 380, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalSlider = QtWidgets.QSlider(self.data_selection)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 510, 311, 22))
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_6 = QtWidgets.QLabel(self.data_selection)
        self.label_6.setGeometry(QtCore.QRect(0, 460, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.data_selection)
        self.label_7.setGeometry(QtCore.QRect(10, 560, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.data_selection)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 270, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_browse = QtWidgets.QPushButton(self.data_selection)
        self.pushButton_browse.setGeometry(QtCore.QRect(110, 120, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 560, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.MplWidget = MplWidget(self.data_selection)
        self.MplWidget.setGeometry(QtCore.QRect(490, 30, 741, 411))
        self.MplWidget.setObjectName("MplWidget")
        self.comboBox_5 = QtWidgets.QComboBox(self.data_selection)
        self.comboBox_5.setGeometry(QtCore.QRect(470, 550, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_17.setGeometry(QtCore.QRect(670, 470, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_totalimage_2 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_totalimage_2.setGeometry(QtCore.QRect(800, 470, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_totalimage_2.setFont(font)
        self.lineEdit_totalimage_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_totalimage_2.setObjectName("lineEdit_totalimage_2")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_19.setGeometry(QtCore.QRect(670, 520, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_19.setReadOnly(False)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_totalclass_2 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_totalclass_2.setGeometry(QtCore.QRect(800, 520, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_totalclass_2.setFont(font)
        self.lineEdit_totalclass_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_totalclass_2.setObjectName("lineEdit_totalclass_2")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_20.setGeometry(QtCore.QRect(900, 470, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_mostclass = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_mostclass.setGeometry(QtCore.QRect(1140, 470, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_mostclass.setFont(font)
        self.lineEdit_mostclass.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_mostclass.setObjectName("lineEdit_mostclass")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_41.setGeometry(QtCore.QRect(900, 520, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_41.setFont(font)
        self.lineEdit_41.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_42.setGeometry(QtCore.QRect(670, 570, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_42.setFont(font)
        self.lineEdit_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_43.setGeometry(QtCore.QRect(670, 620, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_mostpicture = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_mostpicture.setGeometry(QtCore.QRect(1150, 520, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_mostpicture.setFont(font)
        self.lineEdit_mostpicture.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_mostpicture.setObjectName("lineEdit_mostpicture")
        self.lineEdit_lessclass = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_lessclass.setGeometry(QtCore.QRect(910, 570, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_lessclass.setFont(font)
        self.lineEdit_lessclass.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_lessclass.setObjectName("lineEdit_lessclass")
        self.lineEdit_lesspicture = QtWidgets.QLineEdit(self.data_selection)
        self.lineEdit_lesspicture.setGeometry(QtCore.QRect(910, 620, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_lesspicture.setFont(font)
        self.lineEdit_lesspicture.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_lesspicture.setObjectName("lineEdit_lesspicture")
        self.stackedWidget.addWidget(self.data_selection)
        self.train = QtWidgets.QWidget()
        self.train.setObjectName("train")
        self.lineEdit_batch_size = QtWidgets.QLineEdit(self.train)
        self.lineEdit_batch_size.setGeometry(QtCore.QRect(40, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_batch_size.setFont(font)
        self.lineEdit_batch_size.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_batch_size.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_batch_size.setReadOnly(True)
        self.lineEdit_batch_size.setObjectName("lineEdit_batch_size")
        self.spinBox_batch_size = QtWidgets.QSpinBox(self.train)
        self.spinBox_batch_size.setGeometry(QtCore.QRect(200, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.spinBox_batch_size.setFont(font)
        self.spinBox_batch_size.setStyleSheet("color: rgb(255, 255, 255);")
        self.spinBox_batch_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_batch_size.setMaximum(500)
        self.spinBox_batch_size.setObjectName("spinBox_batch_size")
        self.lineEdit_tagetsize = QtWidgets.QLineEdit(self.train)
        self.lineEdit_tagetsize.setGeometry(QtCore.QRect(40, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_tagetsize.setFont(font)
        self.lineEdit_tagetsize.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_tagetsize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tagetsize.setReadOnly(True)
        self.lineEdit_tagetsize.setObjectName("lineEdit_tagetsize")
        self.spinBox_target_size = QtWidgets.QSpinBox(self.train)
        self.spinBox_target_size.setGeometry(QtCore.QRect(200, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.spinBox_target_size.setFont(font)
        self.spinBox_target_size.setStyleSheet("color: rgb(255, 255, 255);")
        self.spinBox_target_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_target_size.setMaximum(500)
        self.spinBox_target_size.setObjectName("spinBox_target_size")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.train)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 190, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.spinBox_epochs = QtWidgets.QSpinBox(self.train)
        self.spinBox_epochs.setGeometry(QtCore.QRect(200, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.spinBox_epochs.setFont(font)
        self.spinBox_epochs.setStyleSheet("color: rgb(255, 255, 255);")
        self.spinBox_epochs.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_epochs.setObjectName("spinBox_epochs")
        self.pushButton_train_2 = QtWidgets.QPushButton(self.train)
        self.pushButton_train_2.setGeometry(QtCore.QRect(60, 350, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_train_2.setFont(font)
        self.pushButton_train_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_train_2.setObjectName("pushButton_train_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.train)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 30, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.train)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 430, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.comboBox_4 = QtWidgets.QComboBox(self.train)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 510, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.widget = widget(self.train)
        self.widget.setGeometry(QtCore.QRect(460, 50, 741, 641))
        self.widget.setObjectName("widget")
        self.checkBox_deep = QtWidgets.QCheckBox(self.train)
        self.checkBox_deep.setGeometry(QtCore.QRect(20, 260, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_deep.setFont(font)
        self.checkBox_deep.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_deep.setObjectName("checkBox_deep")
        self.checkBox_transfer = QtWidgets.QCheckBox(self.train)
        self.checkBox_transfer.setGeometry(QtCore.QRect(190, 260, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox_transfer.setFont(font)
        self.checkBox_transfer.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_transfer.setObjectName("checkBox_transfer")
        self.stackedWidget.addWidget(self.train)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_data_selection.setText(_translate("MainWindow", "Data Selection"))
        self.pushButton_model_selection.setText(_translate("MainWindow", "Model Selection"))
        self.pushButton_train.setText(_translate("MainWindow", "Train"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Models"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vgg-16"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Vgg-19"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Xception"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Resnet50V2"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Resnet101"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Mobilenet"))
        self.comboBox.setItemText(7, _translate("MainWindow", "InceptionV3"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Nasnetlarge"))
        self.comboBox.setItemText(9, _translate("MainWindow", "EfficientB0"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Resnet152"))
        self.comboBox.setItemText(11, _translate("MainWindow", "MobilenetV2"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Densenet12"))
        self.lineEdit_2.setText(_translate("MainWindow", "Number of Layers:"))
        self.lineEdit_3.setText(_translate("MainWindow", "Input Type:"))
        self.lineEdit_4.setText(_translate("MainWindow", "Output Type:"))
        self.lineEdit.setText(_translate("MainWindow", "Properties"))
        self.pushButton_import.setText(_translate("MainWindow", "Import Data"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">DATA FEATURES</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Data path:"))
        self.label_3.setText(_translate("MainWindow", "Random Reflection Axis:"))
        self.checkBox.setText(_translate("MainWindow", "X"))
        self.checkBox_2.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Random Rotation Angle (Degrees):"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">VALIDATION</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Specify Amount Of Training Data To Use For Validation:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Percentage: "))
        self.checkBox_3.setText(_translate("MainWindow", "Shuffle"))
        self.lineEdit_7.setText(_translate("MainWindow", "Import Image Classification for Training"))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse Data Folder"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Please Choose"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Train"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Validation"))
        self.lineEdit_17.setText(_translate("MainWindow", "Total Image:"))
        self.lineEdit_19.setText(_translate("MainWindow", "Total Class:"))
        self.lineEdit_20.setText(_translate("MainWindow", "The Class with Most Picture:"))
        self.lineEdit_41.setText(_translate("MainWindow", "The Number of Most Picture:"))
        self.lineEdit_42.setText(_translate("MainWindow", "The Class with Least Picture:"))
        self.lineEdit_43.setText(_translate("MainWindow", "The Number of Least Picture:"))
        self.lineEdit_batch_size.setText(_translate("MainWindow", "Batch Size:"))
        self.lineEdit_tagetsize.setText(_translate("MainWindow", "Target Size:"))
        self.lineEdit_6.setText(_translate("MainWindow", "Epochs:"))
        self.pushButton_train_2.setText(_translate("MainWindow", "TRAIN"))
        self.lineEdit_8.setText(_translate("MainWindow", "Set Training Parameters Before Train"))
        self.lineEdit_9.setText(_translate("MainWindow", "Graphs"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Please Choose "))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Model Loss"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Model Accuracy"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Confusion Matrix"))
        self.checkBox_deep.setText(_translate("MainWindow", "Deep Learning"))
        self.checkBox_transfer.setText(_translate("MainWindow", "Transfer Learning"))

from mplwidget import MplWidget
from widget import widget
